---
# file: roles/ffmpeg/tasks/main.yaml

- name: Install package
  tags: [debian, ubuntu]
  become: true
  ansible.builtin.apt:
    state: present
    name: ffmpeg

# https://rpmfusion.org/Howto/Multimedia
- name: Install package
  tags: [fedora]
  become: true
  block:
    - name: Uninstall ffmpeg-free
      ansible.builtin.dnf:
        state: absent
        name: ffmpeg-free

    - name: Install ffmpeg
      ansible.builtin.dnf:
        state: present
        allowerasing: true
        name: ffmpeg

- name: Install package
  tags: [macos]
  become: false
  community.general.homebrew:
    state: present
    name: ffmpeg
