# alacritty.toml: configures Alacritty.

[general]
import = ["theme.toml"]  # Import installed theme, if any

[font]
normal = { family = "JetBrainsMono Nerd Font" }  # Use a Nerd Font
size = 12

[cursor.style]
blinking = "Always"  # Force blinking cursor

[mouse]
hide_when_typing = true  # Hide mouse cursor while typing

[selection]
save_to_clipboard = true  # Copy selection to clipboard

[window]
decorations = "None"  # Disable superfluous window decorations
startup_mode = "Maximized"  # Start maximized by default
option_as_alt = "Both"  # Required for MacOS key bindings

# Common shortcuts:
# - Paste with C-S-v
# - Emit A-{1-9} when pressing C-{1-9}
# - Emit A-{hjkl=} when pressing C-S-{hjkl=}
# - Open URI with C-click outside of `tmux`
# - Select URI with double-click in `tmux`
[keyboard]
bindings = [
{ key = "1", mods = "Control", chars = "\u001b1" },
{ key = "2", mods = "Control", chars = "\u001b2" },
{ key = "3", mods = "Control", chars = "\u001b3" },
{ key = "4", mods = "Control", chars = "\u001b4" },
{ key = "5", mods = "Control", chars = "\u001b5" },
{ key = "6", mods = "Control", chars = "\u001b6" },
{ key = "7", mods = "Control", chars = "\u001b7" },
{ key = "8", mods = "Control", chars = "\u001b8" },
{ key = "9", mods = "Control", chars = "\u001b9" },
{ key = "h", mods = "Shift|Control", chars = "\u001bh" },
{ key = "j", mods = "Shift|Control", chars = "\u001bj" },
{ key = "k", mods = "Shift|Control", chars = "\u001bk" },
{ key = "l", mods = "Shift|Control", chars = "\u001bl" },
{ key = "+", mods = "Shift|Control", chars = "\u001b=" },
]
