# Workflow that runs CI checks.
name: CI

# Trigger the workflow on push or pull request events on the `main` branch.
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

  # Allow running this workflow manually from the `Actions` tab.
  workflow_dispatch:

jobs:
  check:
    runs-on: codeberg-tiny
    steps:
      # Sets up user and permissions.
      - uses: https://codeberg.org/andreihh/setup-user@main

      # Checks out the repository under `GITHUB_WORKSPACE`.
      - uses: https://code.forgejo.org/actions/checkout@v4

      - name: Install pre-commit checks
        run: |
          export PATH="${HOME}/.local/bin:${PATH}"
          pipx ensurepath && ensurepath --global
          pipx install pre-commit
          pre-commit install && pre-commit autoupdate

      - name: Run pre-commit checks
        run: pre-commit run --all-files --verbose
