---
# file: roles/java/tasks/main.yaml

- name: Install apt package
  when: ansible_distribution in ["Debian", "Ubuntu"]
  become: true
  ansible.builtin.apt:
    state: present
    name: openjdk-23-jdk

- name: Install dnf package
  when: ansible_distribution in ["Fedora"]
  become: true
  ansible.builtin.dnf:
    state: present
    name: java-latest-openjdk-devel

- name: Install brew formula
  when: ansible_distribution in ["MacOSX"]
  become: false
  community.general.homebrew:
    state: present
    name: openjdk
