---
# file: roles/alacritty/tasks/main.yaml

- name: Install toolchain
  when: ansible_distribution in ["Debian", "Ubuntu", "Fedora"]
  block:
    - name: Install packages
      become: true
      ansible.builtin.package:
        state: present
        name: [alacritty, fontconfig]

    - name: Download Nerd Font
      become: false
      vars:
        nerd_fonts: https://github.com/ryanoasis/nerd-fonts/releases/latest
      ansible.builtin.unarchive:
        src: "{{ nerd_fonts }}/download/JetBrainsMono.zip"
        dest: "{{ ansible_env.XDG_DATA_HOME }}/fonts/"
        remote_src: true

    - name: Refresh font cache
      become: false
      changed_when: true
      ansible.builtin.command: fc-cache -fv

# TODO: ansible.builtin.alternatives x-terminal-emulator

- name: Install brew casks
  when: ansible_distribution in ["MacOSX"]
  become: false
  community.general.homebrew_cask:
    state: present
    name: [alacritty, font-jetbrains-mono-nerd-font]

- name: Install themes
  become: false
  ansible.builtin.git:
    repo: "https://github.com/alacritty/alacritty-theme.git"
    version: master
    depth: 1
    dest: "{{ ansible_env.XDG_CONFIG_HOME }}/alacritty/themes"
