---
# file: roles/ssh/tasks/main.yaml

- name: Ensure agent forwarding is not disabled
  when: ansible_distribution in ["Debian", "Ubuntu", "Fedora", "RedHat"]
  become: true
  ansible.builtin.lineinfile:
    state: absent
    path: /etc/ssh/sshd_config
    regexp: "^\\s*AllowAgentForwarding\\s+no\\s*#?.*"

- name: Configure SSH multiplexing
  become: false
  when: lookup('ansible.builtin.env', 'CLOUD_HOST') | ansible.builtin.mandatory
  ansible.builtin.blockinfile:
    state: present
    create: true
    path: ~/.ssh/config
    mode: u=rw
    append_newline: true
    prepend_newline: true
    block: |
      Match host {{ lookup('ansible.builtin.env', 'CLOUD_HOST') }}
        # Required for SSH multiplexing:
        ControlMaster auto
        ControlPath ~/.ssh/ctrl-%C
        ControlPersist yes
        ForwardAgent yes  # Only for trusted hosts
