#!/bin/bash

# Xprofile: loads `Xresources` and `${COLORSCHEME}` using `xrdb`.
#
# See: https://wiki.archlinux.org/title/Xprofile.

xrdb -m "${XDG_CONFIG_HOME:-$HOME/.config}/X11/Xresources"
xrdb -m \
  "${XDG_CONFIG_HOME:-$HOME/.config}/X11/Xcolors/${COLORSCHEME}.Xresources"
