---
# file: roles/lazygit/tasks/main.yaml

- name: Add COPR repository
  when: ansible_distribution in ["Fedora"]
  become: true
  community.general.copr:
    state: enabled
    name: atim/lazygit

- name: Install package
  when: ansible_distribution in ["Debian", "Ubuntu", "Fedora"]
  become: true
  ansible.builtin.package:
    state: present
    name: lazygit

- name: Install brew formula
  when: ansible_distribution in ["MacOSX"]
  become: false
  community.general.homebrew:
    state: present
    name: lazygit
