---
# file: roles/go/tasks/main.yaml

- name: Install apt package
  when: ansible_distribution in ["Debian", "Ubuntu"]
  become: true
  ansible.builtin.apt:
    state: present
    name: golang-go

- name: Install dnf package
  when: ansible_distribution in ["Fedora"]
  become: true
  ansible.builtin.dnf:
    state: present
    name: golang

- name: Install brew formula
  when: ansible_distribution in ["MacOSX"]
  become: false
  community.general.homebrew:
    state: present
    name: go
