#!/bin/bash -e
#
# Installs `fzf` from sources for Linux systems.
#
# Requires `git`.
#
# This is needed because the `fzf` version available in package managers is too
# old and doesn't support shell completion (requires version 0.48.0 or newer).

[[ $# -gt 0 ]] && echo "Usage: $0" && exit 1

readonly FZF_DIR="${HOME}/.local/src/fzf"

echo "Installing 'fzf'..."

echo "Cleaning up prior 'fzf' installation..."
rm -rf "${FZF_DIR}"

echo "Downloading 'fzf'..."
git clone --depth 1 https://github.com/junegunn/fzf.git "${FZF_DIR}"

echo "Running 'fzf' installer..."
"${FZF_DIR}/install" --bin

echo "Setting up 'fzf' symlink in user 'bin'..."
ln -sfv "${FZF_DIR}/bin/fzf" "${HOME}/.local/bin/fzf"

echo "Setting up 'man' pages for 'fzf'..."
cp -r "${FZF_DIR}/man" "${XDG_DATA_HOME:?}/man"
mandb --no-purge

echo "Configuring 'fzf' shell integration..."
cat << 'EOF' > "${XDG_CONFIG_HOME:?}/bash.d/00-fzf_integration.sh"
# fzf_integration.sh: loads `fzf` shell integration.
#
# Auto-generated by `fzf` installer.
#
# shellcheck shell=bash

# Shell keymaps for `fzf`:
# - <C-r> = search command history
# - **<tab> = complete path / process id / etc.
command -v fzf &> /dev/null && eval "$(fzf --bash)"
EOF

echo "Installed 'fzf' successfully!"
