#!/bin/bash -e
#
# Installs `pyenv` for Linux or MacOS systems.
#
# Requirements:
# - MacOS: Homebrew

[[ $# -gt 0 ]] && echo "Usage: $0" && exit 1

readonly CONFIG_HOME="${XDG_CONFIG_HOME:-${HOME}/.config}"

echo "Installing 'pyenv'..."
if command -v brew &> /dev/null; then
  brew install pyenv
else
  curl -fsSL https://pyenv.run | bash
fi

echo "Configuring 'pyenv' shell integration..."
cat << 'EOF' > "${CONFIG_HOME}/bash.d/00-pyenv_integration.sh"
# pyenv_integration.sh: loads `pyenv` shell integration.
#
# Auto-generated by `pyenv` installer.
#
# shellcheck shell=bash

[[ -d "${PYENV_ROOT}/bin" ]] \
  && export PATH="${PYENV_ROOT}/bin:${PATH}" \
  && eval "$(pyenv init - bash)"
EOF

echo "Installed 'pyenv' successfully!"
