# sonokai.toml: Sonokai color scheme for Alacritty.
#
# See: https://github.com/sainnhe/sonokai.

[colors.primary]
foreground = "#e2e2e3"  # fg
background = "#2c2e34"  # bg0

[colors.normal]
black = "#181819"  # black
red = "#fc5d7c"  # red
green = "#9ed072"  # green
yellow = "#e7c664"  # yellow
blue = "#76cce0"  # blue
magenta = "#b39df3"  # purple
cyan = "#f39660"  # orange
white = "#e2e2e3"  # fg

[colors.bright]
black = "#7f8490"  # gray
red = "#fc5d7c"  # red
green = "#9ed072"  # green
yellow = "#e7c664"  # yellow
blue = "#76cce0"  # blue
magenta = "#b39df3"  # purple
cyan = "#f39660"  # orange
white = "#e2e2e3"  # fg

[colors.cursor]
text = "#2c2e34"  # bg0
cursor = "#e2e2e3"  # fg

[colors.selection]
text = "CellForeground"
background = "#414550"  # bg4
