# alacritty.toml: configures Alacritty.

[general]
import = ["colorscheme.toml"]  # Color scheme inferred from `${COLORSCHEME}`

[font]
normal = { family = "JetBrainsMono Nerd Font" }  # Use a Nerd Font
size = 12

[cursor.style]
blinking = "Always"  # Force blinking cursor

[window]
decorations = "None"  # Disable superfluous window decorations
startup_mode = "Maximized"  # Start maximized by default
option_as_alt = "Both"  # Required for MacOS key bindings

[selection]
save_to_clipboard = true  # Copy selection to clipboard

# Common shortcuts:
# - Paste with C-S-v
# - Exit with C-q
# - Emit A-# when pressing C-#
# - Open URI with C-click outside of `tmux`
# - Select URI with double-click in `tmux`
[keyboard]
bindings = [
{ key = "Q", mods = "Control", action = "Quit" },
{ key = "1", mods = "Control", chars = "\u001b1" },
{ key = "2", mods = "Control", chars = "\u001b2" },
{ key = "3", mods = "Control", chars = "\u001b3" },
{ key = "4", mods = "Control", chars = "\u001b4" },
{ key = "5", mods = "Control", chars = "\u001b5" },
{ key = "6", mods = "Control", chars = "\u001b6" },
{ key = "7", mods = "Control", chars = "\u001b7" },
{ key = "8", mods = "Control", chars = "\u001b8" },
{ key = "9", mods = "Control", chars = "\u001b9" },
]
