---
# file: roles/ghostty/tasks/main.yaml
# https://ghostty.org/docs/install/binary

# TODO: support Debian

- name: Install snap package
  when: ansible_distribution in ["Ubuntu"]
  become: true
  community.general.snap:
    state: present
    classic: true
    name: ghostty

- name: Install COPR package
  when: ansible_distribution in ["Fedora"]
  become: true
  block:
    - name: Add COPR repository
      community.general.copr:
        state: enabled
        name: pgdev/ghostty

    - name: Install from COPR repository
      ansible.builtin.dnf:
        state: present
        name: ghostty

- name: Install and configure as default terminal
  when: ansible_distribution in ["Debian", "Ubuntu", "Fedora"]
  block:
    - name: Fetch binary location
      become: false
      register: binary
      changed_when: false
      ansible.builtin.command: which ghostty

    - name: Configure as default terminal
      become: true
      community.general.alternatives:
        name: x-terminal-emulator
        path: "{{ binary.stdout }}"
        link: /usr/bin/x-terminal-emulator

- name: Install brew cask
  when: ansible_distribution in ["MacOSX"]
  become: false
  community.general.homebrew_cask:
    state: present
    name: ghostty
